---
- name: Configurar Load Balancer Group en DataPower
  hosts: datapower
  gather_facts: no
  vars:
    backend_servers:
      - { ip: "192.168.1.20", port: 8080 }
      - { ip: "192.168.1.21", port: 8080 }
      - { ip: "192.168.1.22", port: 8080 }

  tasks:
    - name: Crear Load Balancer Group en DataPower
      community.general.datapower_lb_group:
        host: "{{ inventory_hostname }}"
        user: "admin"
        password: "password"
        name: "MyLoadBalancerGroup"
        servers: "{{ backend_servers }}"
        state: present