---
- name: Configurar HAProxy para balancear cargas entre DataPower
  hosts: haproxy_server
  become: yes
  vars:
    datapower_servers:
      - { ip: "192.168.1.10", port: 80 }
      - { ip: "192.168.1.11", port: 80 }
      - { ip: "192.168.1.12", port: 80 }
    haproxy_config_file: "/etc/haproxy/haproxy.cfg"

  tasks:
    - name: Instalar HAProxy
      ansible.builtin.apt:
        name: haproxy
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Crear configuración de HAProxy
      ansible.builtin.template:
        src: haproxy.cfg.j2
        dest: "{{ haproxy_config_file }}"
        owner: root
        group: root
        mode: '0644'

    - name: Reiniciar HAProxy
      ansible.builtin.service:
        name: haproxy
        state: restarted
        enabled: yes