---
- name: Realizar ping y guardar salida sin sobrescribir
  hosts: all
  gather_facts: false

  tasks:
    - name: Hacer ping
      ping:
      register: ping_result

    - name: Guardar línea en archivo local sin sobrescribir
      delegate_to: localhost
      run_once: false
      lineinfile:
        path: "./results/ping_output_networl_scan.txt"
        line: "{{ inventory_hostname }} - {{ 'ÉXITO' if ping_result.ping == 'pong' else 'FALLÓ' }}"
        create: yes
